//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostosObras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adicionales
    {
        public int id { get; set; }
        public int idproyecto { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> monto { get; set; }
    
        public virtual proyecto proyecto { get; set; }
    }
}
