//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostosObras.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CostosObraEntities : DbContext
    {
        public CostosObraEntities()
            : base("name=CostosObraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adicionales> adicionales { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<concepto> concepto { get; set; }
        public virtual DbSet<ctacte> ctacte { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<proyecto> proyecto { get; set; }
        public virtual DbSet<rubro> rubro { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
