//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostosObras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyecto()
        {
            this.adicionales = new HashSet<adicionales>();
            this.ctacte = new HashSet<ctacte>();
        }
    
        public int id { get; set; }
        public string observacion { get; set; }
        public int idcliente { get; set; }
        public Nullable<decimal> costototal { get; set; }
        public Nullable<decimal> costoreal { get; set; }
        public byte[] archivo { get; set; }
        public string nombrearchivo { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adicionales> adicionales { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctacte> ctacte { get; set; }
    }
}
